# -*- coding: utf-8 -*-
"""StringSimilarity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uhgGlcBo3bajqwAK2zMX7QJEECffvrfN
"""

import numpy as np
from collections import Counter


class StringSet():

  string_set : set = None
  cardinality : int = 0

  def __init__(self,string : str, ngram : int = 1):
    ngrams = Counter(string,ngram)
    self.string_set = set(ngrams.keys())
    self.cardinality = len(self.string_set)
  
  def intersection(self, other):
    








def jaccard(s1:str,s2:str)->float:
  s1, s2 = set(s1), set(s2)
  return np.divide()